### PR TITLE
Resolve errors caused by the readiness and liveness probes for the airflow webserver and update the github link and subPath

### PR DESCRIPTION
**Pull request by JeetRH**
Increased the initialDelaySeconds for the readinessProbe to 45 secs and the initialDelaySeconds for the livenessProbe to 60 secs. With this change the readiness probe fails once for each webserver pod and then succeeds. The livenessProbe succeeds without any errors.

Earlier, the readinessProbe on each pod was failing many times and exceeding the failureThreshold and restarting the pod. Also the livenessProbe was conflicting with the readinessProbe and failing as well.

Also updated the GitHub link to point to the current repo and subPath to match the folder name. I have still kept them commented as before.

### CODE REVIEW

**Comment by strangiato** [comment]
@JeetRH looks like some extra stuff may have made it into your PR.

Looks like the dag example and also the repo points to your fork now instead of the main branch.  Can you separate out the dag updates and the probe updates into separate PRs?

**Comment by JeetRH** [comment]
Creating another one

**Comment by JeetRH** [comment]
@strangiato Extra stuff is removed. Have just updated the GitHub link and subPath as the previous one is wrong

**Comment by strangiato** [comment]
@codekow the probe updates were causing pods to restart before they had finished starting up.  I had @JeetRH  do some testing to try and determine what the best update to the default delay was and we ended up settling on 45 sec.

Let us know if you have any issues or concerns here.

**Comment by codekow** [comment]
@JeetRH @strangiato Great work guys. Thanks.

**Pull request merged**
